version: "3"
networks:
  safeMedicine:
    external: false

services:
  frontend:
    container_name: frontend
    image: frontend:latest
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
    networks:
      - safeMedicine
    ports:
      - 4200:80
  backend:
    container_name: backend
    image: backend:latest
    build:
      context: ./backend
      args:
        - OPENAI_TOKEN=${OPENAI_TOKEN}
    networks:
      - safeMedicine
    ports:
      - 8081:8081
